name = "aws-docs-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.development]
name = "aws-docs-mcp-server-dev"

[env.production]
name = "aws-docs-mcp-server-prod"

[vars]
AWS_DOCUMENTATION_PARTITION = "aws"
FASTMCP_LOG_LEVEL = "ERROR"